### PR TITLE
improve vulkan

### PR DESCRIPTION
**Pull request by hypengw**
support modeling,interaction,topology with vulkan
require vulkan 1.2 and c++ 17

### CODE REVIEW

**Review by clouddon — CHANGES_REQUESTED** [review]
The SortByKey algaorithm crashes, VkProgram also contains a lot of compilation issues

**Comment by hypengw** [comment]
tested with `Test_Core` and `Qt_Pickers`.

**Comment by hypengw** [comment]
@clouddon 
Any plan to merge this?

**Review by clouddon — CHANGES_REQUESTED** [review]
SortByKey still crashes when I test with App_GLPointVisualModule and App_GLSurfaceVisualModule

**Comment by hypengw** [comment]
fix arr component
use common modeling files
add triangle merge func
add interaction mergeIndex func

**Pull request closed without merging**
